function bunch_of_particles    
    close all;
    particle_number = 4.5e8;
    
    fake_z_pot = -35.2e-3;
    pmash_min = Particle('PMASH particles MIN', (190e-9)/2, 1060, -35.2e-3, 1);
    core_shell_min = Particle('MS/CS particles MIN', (240e-9)/2, 1650, -38.6e-3, 1);
    pmash_avg = Particle('PMASH particles AVG', (200e-9)/2, 1060, -35.2e-3, 1);
    core_shell_avg = Particle('MS/CS particles AVG', (250e-9)/2, 1650, -38.6e-3, 1);
    pmash_max= Particle('PMASH particles MAX', (210e-9)/2, 1060, -35.2e-3, 1);
    core_shell_max = Particle('MS/CS particles MAX', (260e-9)/2, 1650, -38.6e-3, 1);
    
    normal_particles = [pmash_min, pmash_avg, pmash_max, ...
                        core_shell_min, core_shell_avg, core_shell_max];
    normal_particles = [pmash_avg, core_shell_avg];
    
    silica_particles = [Particle.SilicaParticle((462e-9)/2), ...
                        Particle.SilicaParticle((7000e-9)/2), ...
                        Particle.SilicaParticle((150e-9)/2)];                          
    
    gold_xia_particles = [Particle('Non-PEG 15nm Gold', (22.5e-9)/2, 6290, fake_z_pot, 120), ...
                          Particle('Non-PEG 54nm Gold', (77.7e-9)/2, 7010, fake_z_pot, 20), ...
                          Particle('Non-PEG 100nm Gold', (127.3e-9)/2, 9820, fake_z_pot, 2.8), ...
                          Particle('PEG 15nm Gold', (20.5e-9)/2, 7970, fake_z_pot, 120), ...
                          Particle('PEG 54nm Gold', (71.6e-9)/2, 8680, fake_z_pot, 20), ...
                          Particle('PEG 100nm Gold', (116.3e-9)/2, 12570, fake_z_pot, 2.8)];
    
    leo_particles = [Particle('235nm SiO2', 235e-9/2, 1850, fake_z_pot, 1), ...#not sure about these densities
                     Particle('519nm SiO2', 519e-9/2, 1850, fake_z_pot, 1), ...
                     Particle('60nm Au', 60e-9/2, 19300, fake_z_pot, 1), ...
                     Particle('110nm Au', 110e-9/2, 19300, fake_z_pot, 1)];                 
                      
    normal_time = 24*60*60;
    
    leo_conditions = [ExperimentalCondition.StandardCondition(normal_time, .268, 1), ... 
                      ExperimentalCondition.StandardCondition(normal_time, .268, 2)];
    
    
    normal_conditions = [ExperimentalCondition.StandardCondition(normal_time, .0053, c.no_cells), ...
                         ExperimentalCondition.StandardCondition(normal_time, .0053, c.upright_cells), ...
                         ExperimentalCondition.StandardCondition(normal_time, .002, c.inverted_cells), ...
                         ExperimentalCondition.StandardCondition(normal_time, .002, c.vertical_cells), ...
                         ExperimentalCondition.StandardCondition(normal_time, .0053, c.upright_cells_linear), ...
                         ExperimentalCondition.StandardCondition(normal_time, .002, c.inverted_cells_linear), ...
                         ExperimentalCondition.StandardCondition(normal_time, .002, c.vertical_cells_linear)];                      
    normal_conditions = [ExperimentalCondition.StandardCondition(normal_time, .0053, c.upright_cells), ...
                         ExperimentalCondition.StandardCondition(normal_time, .0053, c.upright_cells_linear), ...
                         ExperimentalCondition.StandardCondition(normal_time, .0053, c.upright_cells_logistic)];
                            
    %lison particles for experiment 2 
    lison_particles = [Particle.SilicaParticle(29.3e-9)];
    
    lison_conditions_exp_2 = [ExperimentalCondition.StandardCondition(normal_time, 40e-9/3.6e-5, 1), ...
        ExperimentalCondition.StandardCondition(normal_time, 40e-9/3.6e-5, 2), ...
        ExperimentalCondition.StandardCondition(normal_time, 80e-9/3.6e-5, 2), ...
        ExperimentalCondition.StandardCondition(normal_time, 120e-9/3.6e-5, 2), ...
        ExperimentalCondition.StandardCondition(normal_time, 160e-9/3.6e-5, 2), ...
        ExperimentalCondition.StandardCondition(normal_time, 200e-9/3.6e-5, 2), ...
        ExperimentalCondition.StandardCondition(normal_time, 240e-9/3.6e-5, 2)];

    %lison_particles2 = 
    
    six_hours = 6 * 60 * 60;
    lison_conditions_fig_5 = [ExperimentalCondition.StandardCondition(six_hours, 90e-9/8.1e-5, 1), ...
        ExperimentalCondition.StandardCondition(six_hours, 90e-9/8.1e-5*2, 2), ...
        ExperimentalCondition.StandardCondition(six_hours, 180e-9/8.1e-5*2, 2), ...
        ExperimentalCondition.StandardCondition(six_hours, 270e-9/8.1e-5*2, 2), ...
        ExperimentalCondition.StandardCondition(six_hours, 360e-9/8.1e-5*2, 2), ...
        ExperimentalCondition.StandardCondition(six_hours, 450e-9/8.1e-5*2, 2)];
        
    win_feng_particles = [Particle('50nm PS', (50e-9)/2, 1050, fake_z_pot, 1), ...
        Particle('100nm PS', (100e-9)/2, 1050, fake_z_pot, 1), ...
        Particle('200nm PS', (200e-9)/2, 1050, fake_z_pot, 1), ...
        Particle('500nm PS', (500e-9)/2, 1050, fake_z_pot, 1), ...
        Particle('1000nm PS', (1000e-9)/2, 1050, fake_z_pot, 1)];
    
    win_feng_conditions = [ExperimentalCondition.PhysiologicalCondition(1*60*60, 1e-7/3.6e-5, 1), ...
        ExperimentalCondition.PhysiologicalCondition(2*60*60, 1e-7/3.6e-5, 2)];
    
    
    particles = normal_particles;
    conditions = normal_conditions;
    condition_base_len = conditions(1).len;
    
    
    m = length(conditions);
    n = length(particles);
    fig_per_plot = 0;
    
    
end


